CREATE TABLE IF NOT EXISTS Dash_VinDecodes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  vin CHAR(17) NOT NULL,
  source VARCHAR(50) NOT NULL DEFAULT 'nhtsa-vpic',
  make VARCHAR(100) NULL,
  model VARCHAR(150) NULL,
  model_year SMALLINT UNSIGNED NULL,
  trim_name VARCHAR(150) NULL,
  vehicle_type VARCHAR(150) NULL,
  body_class VARCHAR(200) NULL,
  drive_type VARCHAR(100) NULL,
  engine_configuration VARCHAR(100) NULL,
  engine_cylinders TINYINT UNSIGNED NULL,
  engine_displacement_l DECIMAL(5,2) NULL,
  engine_model VARCHAR(150) NULL,
  engine_manufacturer VARCHAR(150) NULL,
  engine_hp DECIMAL(8,2) NULL,
  fuel_type_primary VARCHAR(100) NULL,
  fuel_type_secondary VARCHAR(100) NULL,
  electrification_level VARCHAR(150) NULL,
  transmission_style VARCHAR(150) NULL,
  transmission_speeds TINYINT UNSIGNED NULL,
  turbo VARCHAR(50) NULL,
  doors TINYINT UNSIGNED NULL,
  seats TINYINT UNSIGNED NULL,
  gvwr VARCHAR(200) NULL,
  plant_city VARCHAR(100) NULL,
  plant_state VARCHAR(100) NULL,
  plant_country VARCHAR(100) NULL,
  error_code VARCHAR(50) NULL,
  error_text TEXT NULL,
  raw_response JSON NOT NULL,
  decoded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY Dash_VinDecodes_vin_unique (vin),
  KEY Dash_VinDecodes_make_year_idx (make, model_year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
